root = "."
tmp_dir = "tmp"

[build]
  entrypoint = "tmp/main"
  cmd = "go build -o tmp/main ./cmd/server"
  bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp"]
  
[log]
  main_only = false